In [ ]:
"""檢查檔案
"""

import os


def check_folders_for_same_files(path):
    files_sets = []  # 儲存每個資料夾中的檔案集合

    # 列出指定路徑下的所有檔案與資料夾
    for root, dirs, files in os.walk(path):
        # 只處理資料夾而非子資料夾
        if root == path:
            for folder in dirs:
                folder_path = os.path.join(root, folder)
                files_set = set()  # 建立空的檔案集合
                for file in os.listdir(folder_path):
                    files_set.add(file)  # 將檔案加入集合
                files_sets.append(files_set)  # 將集合加入列表

    # 檢查所有資料夾中的檔案集合是否都相同
    return all(files_set == files_sets[0] for files_set in files_sets)


# 指定要檢查的路徑
folder_path = r"C:\Users\D\Desktop\0228\人口"

# 獲取結果
result = check_folders_for_same_files(folder_path)

# 輸出結果
if result:
    print("每個資料夾中都含有相同的檔案。")
else:
    print("資料夾中含有不同的檔案。")

# 入手的excel 不確定編碼可以使用這一個

In [ ]:
def read_file_with_encoding(file_path):
    import pandas as pd

    # 定義可能的編碼方式列表
    encodings = ["utf-8", "big5", "gbk"]
    for encoding in encodings:
        try:
            df = pd.read_csv(file_path, encoding=encoding)
            return df, encoding  # 如果成功讀取，則返回DataFrame和使用的編碼方式
        except UnicodeDecodeError:
            pass  # 如果出現解碼錯誤，繼續嘗試下一個編碼方式
    # return None, None  # 如果沒有成功讀取，則返回None和None
    return None, None

# 無索引合併

In [ ]:
"""
主要程式碼
主要修改 folder_path
輸入一堆檔案
輸出一個合併的pd
"""

import os
import pandas as pd

# 指定要合併的資料夾路徑
folder_path = r"C:\Users\student\Desktop\0228\人口\八里區112年人口"

# 建立一個空的DataFrame來存儲檔案內容
dataframes = []
encodings = ["utf-8", "big5", "gbk"]

# 列出指定路徑下的所有檔案
for root, dirs, files in os.walk(folder_path):
    for file in files:
        file_path = os.path.join(root, file)
        # 使用自定義函式來讀取檔案，並獲得所使用的編碼方式
        df, encoding = read_file_with_encoding(file_path)
        if df is not None:
            dataframes.append(df)
            # print(encoding)
        else:
            print(f"無法成功讀取檔案 {file}")

# 使用concat函式將所有DataFrame合併
result_df = pd.concat(dataframes, axis=0)

# 輸出合併後的DataFrame
print(result_df)

# 存檔 \
save_dataframe_csv_excel(變數名稱, "輸出檔案名")
save_dataframe_excel_and_open(變數名稱, "輸出檔案名")

In [ ]:
save_dataframe_csv_excel(變數名稱, "輸出檔案名")

In [2]:
import pandas as pd
import os


def save_dataframe_csv_excel(df, filename):
    """
    將 DataFrame 存儲為 CSV 和 Excel 檔案，並打開 Excel 檔案。

    Args:
        df (pandas.DataFrame): 要存儲的 DataFrame。
        filename (str): 要保存的文件名，不包含檔案擴展名。
    """
    # 將 DataFrame 存儲為 CSV 檔案
    csv_filename = filename + ".csv"
    df.to_csv(csv_filename, index=False, encoding="utf-8")
    print(f"已保存為 CSV 檔案：{csv_filename}")

    # 將 DataFrame 存儲為 Excel 檔案
    excel_filename = filename + ".xlsx"
    df.to_excel(excel_filename, index=False)
    print(f"已保存為 Excel 檔案：{excel_filename}")

    # 打開 Excel 檔案
    os.startfile(excel_filename)
    print("已打開 Excel 檔案")


def save_dataframe_excel_and_open(df, filename):
    """
    將 DataFrame 存儲為Excel 檔案，並打開 Excel 檔案。

    Args:
        df (pandas.DataFrame): 要存儲的 DataFrame。
        filename (str): 要保存的文件名，不包含檔案擴展名。
    """

    # 將 DataFrame 存儲為 Excel 檔案
    excel_filename = filename + ".xlsx"
    df.to_excel(excel_filename, index=False)
    print(f"已保存為 Excel 檔案：{excel_filename}")

    # 打開 Excel 檔案
    os.startfile(excel_filename)
    print("已打開 Excel 檔案")


# 使用範例
# save_dataframe_csv_excel(變數名稱, "輸出檔案名")

# 資料處理

In [ ]:
file_path = r".\output.csv"
# encodings_to_try = ['utf-8', 'big5', 'gbk']  # 定義要嘗試的編碼方式列表

# 使用自定義函數嘗試不同的編碼方式來讀取檔案
data, successful_encoding = read_file_with_encoding(file_path)

if data is not None:
    # 如果成功讀取到資料
    print(f"成功使用編碼方式 '{successful_encoding}' 讀取檔案。")
    # 在這裡可以進行資料處理和分析
    # 例如，排序資料並計算年齡分組的總人數
    data_sorted = data.sort_values(by="年齡")
    age_group_totals = data_sorted.groupby("年齡").sum()

    print(age_group_totals)
else:
    print("無法使用任何編碼方式讀取檔案。")

In [ ]:
import pandas as pd

# 讀取檔案並嘗試不同的編碼方式
file_path = r".\output.csv"
data, successful_encoding = read_file_with_encoding(file_path)

if data is not None:
    # 如果成功讀取到資料
    print(f"成功使用編碼方式 '{successful_encoding}' 讀取檔案。")
    # 在這裡可以進行資料處理和分析
    # 例如，排序資料並計算年齡分組的總人數
    data_sorted = data.sort_values(by="年齡")
    age_group_totals = data_sorted.groupby("年齡").sum()

    # 將排序後的年齡加在 DataFrame 的第一行
    concatenated_data = pd.concat(
        [age_group_totals, age_group_totals.iloc[:, 0]], axis=1
    )

    save_dataframe_to_files(concatenated_data, "concatenatedData")
    print(concatenated_data)
else:
    print("無法使用任何編碼方式讀取檔案。")

In [ ]:
age_group_totals.iloc[:, 0]

# 當資料都放在同一張ods

In [ ]:
pip install odfpy -q
print("OK")

import pandas as pd

file_path = r"C:\Users\student\Desktop\0228\台北市112年1-12月各區按年齡人口數.ods"

tapi_dataframe = pd.read_excel(file_path, engine="odf")
tapi_dataframe

# 找時間整理下前面的，亂七八糟的

In [ ]:
"""找到NAN 和 零值"""

import pandas as pd


file_source_path = r"..\飲料店總表030501.csv"


file_source_pd = pd.read_csv(file_source_path)


# 選擇你想要計算的範圍（假設你想從第5行到最後一行）


selected_range = file_source_pd


# 計算這個範圍內每一欄的空白值(NaN)數量


nan_values_per_column_in_range = selected_range.isnull().sum(axis=0)


# 計算每個欄位的總數據量
total_data_per_column = len(selected_range)


# 計算每個欄位的空白值(NaN)佔比
nan_percentage_per_column = (
    nan_values_per_column_in_range / total_data_per_column
) * 100


# 計算這個範圍內每一欄的零值數量


zero_values_per_column_in_range = (selected_range == 0).sum(axis=0)


# 計算每個欄位的零值佔比


zero_percentage_per_column = (
    zero_values_per_column_in_range / total_data_per_column
) * 100


# 計算每個欄位的零值和NaN值的總數


total_zero_and_nan_per_column = (
    zero_values_per_column_in_range + nan_values_per_column_in_range
)


# 計算每個欄位的零值和NaN值總數的佔比


total_zero_and_nan_percentage_per_column = (
    total_zero_and_nan_per_column / total_data_per_column
) * 100


# 將結果轉換為 DataFrame


values_df = pd.DataFrame(
    {
        "欄位名稱": nan_values_per_column_in_range.index,
        # '零值+NAN數量': total_zero_and_nan_per_column.values,
        "零值+NAN佔比 (%)": total_zero_and_nan_percentage_per_column.values.round(2),
        "空白值(NaN)數量": nan_values_per_column_in_range.values,
        "空白值(NaN)佔比 (%)": nan_percentage_per_column.values.round(2),
        "零值數量": zero_values_per_column_in_range.values,
        "零值佔比 (%)": zero_percentage_per_column.values.round(2),
    }
)


# 列印 DataFrame


# print(values_df)


# 將 DataFrame 存儲到 CSV 檔案中


values_df.to_csv("零值與空白值統計.csv", index=False, encoding="utf-8-sig")


# 可以指定 index=False 避免寫入索引列


values_df_sorted = values_df.sort_values(by="零值+NAN佔比 (%)", ascending=False)


# 篩選出 '零值+NAN佔比 (%)' 大於50的欄位


filtered_values_df = values_df_sorted[values_df_sorted["零值+NAN佔比 (%)"] > 20]


print(filtered_values_df)

# 檢視空值及零值

In [ ]:
analyze_nan_and_zero_values(
    data, threshold, sort_column="零值+NAN佔比 (%)", ascending=False
)

In [6]:
import pandas as pd


def analyze_nan_and_zero_values(
    data, threshold, sort_column="零值+NAN佔比 (%)", ascending=False
):
    """
    檢查0值和 nan 的數量
    threshold 為 百分比，例threshold=20，會回傳 零值+NAN佔比 (%) 大於20% 的
    當 threshold = 0 會回傳全部
    """
    # 如果輸入是文件路徑，讀取CSV文件並轉換成Pandas DataFrame
    if isinstance(data, str):
        file_source_pd = pd.read_csv(data)
    # 如果輸入是Pandas DataFrame，直接使用它
    elif isinstance(data, pd.DataFrame):
        file_source_pd = data
    else:
        raise ValueError(
            "Invalid input type. Input must be either file path or Pandas DataFrame."
        )

    # 計算這個範圍內每一欄的空白值(NaN)數量
    nan_values_per_column_in_range = file_source_pd.isnull().sum(axis=0)

    # 計算每個欄位的總數據量
    total_data_per_column = len(file_source_pd)

    # 計算每個欄位的空白值(NaN)佔比
    nan_percentage_per_column = (
        nan_values_per_column_in_range / total_data_per_column
    ) * 100

    # 計算這個範圍內每一欄的零值數量
    zero_values_per_column_in_range = (file_source_pd == 0).sum(axis=0)

    # 計算每個欄位的零值佔比
    zero_percentage_per_column = (
        zero_values_per_column_in_range / total_data_per_column
    ) * 100

    # 計算每個欄位的零值和NaN值的總數
    total_zero_and_nan_per_column = (
        zero_values_per_column_in_range + nan_values_per_column_in_range
    )

    # 計算每個欄位的零值和NaN值總數的佔比
    total_zero_and_nan_percentage_per_column = (
        total_zero_and_nan_per_column / total_data_per_column
    ) * 100

    # 將結果轉換為 DataFrame
    values_df = pd.DataFrame(
        {
            "欄位名稱": nan_values_per_column_in_range.index,
            "零值+NAN佔比 (%)": total_zero_and_nan_percentage_per_column.values.round(
                2
            ),
            "空白值(NaN)數量": nan_values_per_column_in_range.values,
            "空白值(NaN)佔比 (%)": nan_percentage_per_column.values.round(2),
            "零值數量": zero_values_per_column_in_range.values,
            "零值佔比 (%)": zero_percentage_per_column.values.round(2),
        }
    )

    # 將 DataFrame 存儲到 CSV 檔案中
    values_df.to_csv("零值與空白值統計.csv", index=False, encoding="utf-8-sig")

    # 如果 threshold 等於 0，則返回所有欄位
    if threshold == 0:
        return values_df

    # 篩選出 '零值+NAN佔比 (%)' 大於指定閾值的欄位
    filtered_values_df = values_df[values_df["零值+NAN佔比 (%)"] > threshold]

    # 根據指定的列進行排序
    sorted_values_df = filtered_values_df.sort_values(
        by=sort_column, ascending=ascending
    )

    return sorted_values_df


# 測試
# result_df = analyze_nan_and_zero_values(clean_data, threshold=0, sort_column='欄位名稱', ascending=False)
# print(result_df)

# 補值

In [ ]:
"""取得區里單一列表"""

import pandas as pd

# 首先，準備一個 DataFrame 來存儲結果
file_source_path = r"..\飲料店總表030501.csv"
data = pd.read_csv(file_source_path)

import pandas as pd

quartiles_data = []  # 用來存儲計算結果的列表

# 逐個社區迭代並計算四分位數和中位數
for neighborhood in unique_neighborhoods_list:
    # 篩選出當前社區的數據
    neighborhood_data = data[data["neighborhood"] == neighborhood]

    # 計算每一天的四分位數和中位數
    for day in [
        "Monday_open_hours",
        "Tuesday_open_hours",
        "wendesday_open_hours",
        "Thursday_open_hours",
        "Friday_open_hours",
        "Saturday_open_hours",
        "Sunday_open_hours",
    ]:
        # 篩選出當前社區、當前天的開放時間數據並去除空值
        day_data = neighborhood_data[day].dropna()

        # 如果數據不為空，則計算四分位數和中位數
        if not day_data.empty:
            q1 = day_data.quantile(0.25)
            q2 = day_data.quantile(0.5)
            q3 = day_data.quantile(0.75)

            # 將計算結果存儲到 quartiles_data 列表中
            quartiles_data.append(
                {
                    "neighborhood": neighborhood,
                    "day": day,
                    "Q1": q1,
                    "Median": q2,
                    "Q3": q3,
                }
            )

# 將 quartiles_data 資料存入 DataFrame 中
quartiles_df = pd.DataFrame(quartiles_data)

quartiles_df.to_csv("各里營業時間.csv", index=False, encoding="utf-8-sig")

# 列印 DataFrame
# print(quartiles_df)

In [54]:
import pandas as pd

# 讀取Excel檔案
file_path = "../飲料店總表030501.csv"
file_data_pd = pd.read_csv(file_path)

# 按區分組並獲取每個區的獨特里列表
district_pd = file_data_pd.groupby("district")["neighborhood"].unique().reset_index()
district_pd["neighborhood"] = district_pd["neighborhood"].apply(list)

# 展開列表，使每個里成為單獨的行，並保留相關的區
district_neighborhoods_pd = district_pd.explode("neighborhood")
district_neighborhoods_pd.reset_index(drop=True, inplace=True)

# # 將整理後的數據保存為新的Excel檔案
# output_path = '/mnt/data/Complete_City_File.xlsx'
# exploded_data.to_excel(output_path, index=False)

district_neighborhoods_pd

     district neighborhood
0         三峽區          龍學里
1         三峽區          龍恩里
2         三峽區          永舘里
3         三峽區          龍埔里
4         三峽區          介壽里
...       ...          ...
1065      鶯歌區          鳳福里
1066      鶯歌區          中鶯里
1067      鶯歌區          尖山里
1068      龜山區          龍壽里
1069      龜山區          大崗里

[1070 rows x 2 columns]

# 填補營業時間中位數

In [9]:
""" 填補營業時間中位數
"""

import pandas as pd

filled_source_path = r"..\飲料店總表0307final01_補上人氣_補值_hg.xlsx"

file_data_pd = pd.read_excel(filled_source_path)


# 篩選出不包含空白值的資料
clean_data = file_data_pd.dropna(
    subset=[
        "Monday_open_hours",
        "Tuesday_open_hours",
        "wendesday_open_hours",
        "Thursday_open_hours",
        "Friday_open_hours",
    ]
)

# 按照district和neighborhood分組，並計算每組的Monday_open_hours中位數
district_neighborhood_median_hours = (
    clean_data.groupby(["district", "neighborhood"])[
        [
            "Monday_open_hours",
            "Tuesday_open_hours",
            "wendesday_open_hours",
            "Thursday_open_hours",
            "Friday_open_hours",
        ]
    ]
    .median()
    .reset_index()
)

district_median_hours = (
    clean_data.groupby(["district"])[
        [
            "Monday_open_hours",
            "Tuesday_open_hours",
            "wendesday_open_hours",
            "Thursday_open_hours",
            "Friday_open_hours",
        ]
    ]
    .median()
    .reset_index()
)


# 將中位數資料合併回原始資料中
fill_neighborhood_workday_open_hours_pd = pd.merge(
    file_data_pd,
    district_neighborhood_median_hours,
    on=["district", "neighborhood"],
    how="left",
    suffixes=('', '_neighborhood_median')
)

# 將中位數資料合併回原始資料中
fill_district_workday_open_hours_pd = pd.merge(
    fill_neighborhood_workday_open_hours_pd,
    district_median_hours,
    on=["district"],
    how="left",
    suffixes=('', '_district_median')
)


# # 儲存到Excel檔案
# filename = "三峽龍學理.xlsx"  # Excel檔案名稱
save_dataframe_csv_excel(fill_district_workday_open_hours_pd, "區域中位數填補資料")

已保存為 CSV 檔案：區域中位數填補資料.csv
已保存為 Excel 檔案：區域中位數填補資料.xlsx
已打開 Excel 檔案

In [11]:
""" 收入中位數
"""

# 篩選出不包含空白值的資料
salary_income_median_clean_data_pd = file_data_pd.dropna(
    subset=["salary_income_median"]
)

salary_income_median_district_pd = (
    salary_income_median_clean_data_pd.groupby(["district"])[["salary_income_median"]]
    .median()
    .reset_index()
)

salary_income_median_district_neighborhood_daata_pd = (
    salary_income_median_clean_data_pd.groupby(["district", "neighborhood"])[
        ["salary_income_median"]
    ]
    .median()
    .reset_index()
)

salary_income_median_district_neighborhood_pd = pd.merge(
    fill_district_workday_open_hours_pd,
    salary_income_median_district_neighborhood_daata_pd,
    on=["district", "neighborhood"],
    how="left",
    suffixes=('', '_neighborhood_median')
)

salary_income_median_pd = pd.merge(
    salary_income_median_district_neighborhood_pd,
    salary_income_median_district_pd,
    on=["district"],
    how="left",
    suffixes=('', '_district_median')
)

save_dataframe_csv_excel(salary_income_median_pd, "區域中位數填補資料")

已保存為 CSV 檔案：區域中位數填補資料.csv
已保存為 Excel 檔案：區域中位數填補資料.xlsx
已打開 Excel 檔案

In [8]:
file_path = r"C:\Users\D\Desktop\0307\期末\區域中位數填補資料.xlsx"
df = pd.read_excel(file_path)

analyze_nan_and_zero_values(df, 0, sort_column="零值+NAN佔比 (%)", ascending=False)

,欄位名稱,零值+NAN佔比 (%),空白值(NaN)數量,空白值(NaN)佔比 (%),零值數量,零值佔比 (%)
0,name,0.00,0,0.00,0,0.00
1,star,4.53,0,0.00,215,4.53
2,comment,4.53,0,0.00,215,4.53
3,class,0.00,0,0.00,0,0.00
4,address,0.00,0,0.00,0,0.00
5,latitude,0.00,0,0.00,0,0.00
6,longitude,0.00,0,0.00,0,0.00
7,school_counts,2.45,0,0.00,116,2.45
8,drink_counts,0.00,0,0.00,0,0.00
9,train_counts,83.99,0,0.00,3983,83.99
10,youbike_counts,10.31,0,0.00,489,10.31
11,bus_counts,1.29,0,0.00,61,1.29
12,park_counts,3.33,0,0.00,158,3.33
13,night_market_counts,54.24,0,0.00,2572,54.24
14,sports_facilities_counts,10.27,0,0.00,487,10.27
15,mrt_counts,29.63,0,0.00,1405,29.63
16,movie_theater_counts,60.23,0,0.00,2856,60.23
17,hospital_counts,48.50,0,0.00,2300,48.50
18,district,0.00,0,0.00,0,0.00
19,neighborhood,0.00,0,0.00,0,0.00
20,salary_income_median_x,0.00,0,0.00,0,0.00
21,people_flow_mean,0.00,0,0.00,0,0.00
22,knock_down_price_mean,1.16,0,0.00,55,1.16
23,brand,64.74,3070,64.74,0,0.00
24,Monday_open_hours_x,0.00,0,0.00,0,0.00
25,Tuesday_open_hours_x,0.08,0,0.00,4,0.08
26,wendesday_open_hours_x,0.65,0,0.00,31,0.65
27,Thursday_open_hours_x,0.97,0,0.00,46,0.97
28,Friday_open_hours_x,1.37,0,0.00,65,1.37
29,Saturday_open_hours,28.70,1361,28.70,0,0.00
30,Sunday_open_hours,43.19,2048,43.19,0,0.00
31,weekend_open,28.70,0,0.00,1361,28.70
32,road_area_ratio,0.00,0,0.00,0,0.00
33,age,0.00,0,0.00,0,0.00
34,Monday_open_hours_y,2.74,130,2.74,0,0.00
35,Tuesday_open_hours_y,2.74,130,2.74,0,0.00
36,wendesday_open_hours_y,2.74,130,2.74,0,0.00
37,Thursday_open_hours_y,2.74,130,2.74,0,0.00
38,Friday_open_hours_y,2.74,130,2.74,0,0.00
39,Monday_open_hours,0.00,0,0.00,0,0.00
40,Tuesday_open_hours,0.00,0,0.00,0,0.00
41,wendesday_open_hours,0.00,0,0.00,0,0.00
42,Thursday_open_hours,0.00,0,0.00,0,0.00
43,Friday_open_hours,0.00,0,0.00,0,0.00
44,salary_income_median_y,0.23,11,0.23,0,0.00
45,salary_income_median,0.00,0,0.00,0,0.00
46,weekday_working_hours,100.00,4742,100.00,0,0.00

In [2]:
import pandas as pd

file_path = r"C:\Users\D\Desktop\0307\期末\區域中位數填補資料.xlsx"
df = pd.read_excel(file_path)

test = analyze_nan_and_zero_values(
    df, 0, sort_column="零值+NAN佔比 (%)", ascending=False
)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\D\\Desktop\\0307\\期末\\區域中位數填補資料.xlsx'